inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/initializers/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false


# Plugins à charger
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
