default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password:
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rikiki_score_development

test:
  <<: *default
  database: rikiki_score_test

production:
  <<: *default
  database: rikiki_score_production
  username: rikiki_score
  password: <%= ENV["RIKIKI_SCORE_DATABASE_PASSWORD"] %>
